jobs:
  - name: runSh
    type: runSh
    steps:
      - IN: gitRepo
      - TASK:
        - script: sudo apt-get install -y jq
      - OUT: image
    on_success:
      - script: echo 'successful runSh'
    on_failure:
      - script: echo 'failed runSh'
